[strip_0]
label = "PhysStrip0"
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_1]
label = "PhysStrip1"
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_2]
label = "PhysStrip2"
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0


[strip_3]
label = "PhysStrip3"
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_4]
label = "PhysStrip4"
A1 = true
A2 = true
A3 = true
A4 = true
A5 = true
B1 = true
B2 = true
B3 = true
mono = true
solo = true
mute = true
gain = 0.0

[strip_5]
label = "VirtStrip0"
A3 = true
A5 = true

[strip_6]
label = "VirtStrip1"
limit = -12
k = 3

[strip_7]
label = "VirtStrip2"
mc = true

[bus_0]
label = "PhysBus0"
eq = false
mute = false
gain = 0.0

[bus_1]
label = "PhysBus1"
eq = false
mute = false
gain = 0.0

[bus_2]
label = "PhysBus2"
eq = false
mute = false
gain = 0.0

[bus_3]
label = "PhysBus3"
eq = false
mute = false
gain = 0.0

[bus_4]
label = "PhysBus4"
eq = false
mute = false
gain = 0.0

[bus_5]
label = "VirtBus0"

[bus_6]
label = "VirtBus1"
gain = -22.8

[bus_7]
label = "VirtBus2"
