[strip_0]
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_1]
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_2]
A1 = true
A2 = true
A3 = true
A4 = true
A5 = true
B1 = true
B2 = true
B3 = true
mono = true
solo = true
mute = true
gain = 0.0

[strip_3]
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[strip_4]
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
mono = false
solo = false
mute = false
gain = 0.0

[bus_0]
eq = false
mute = false
gain = 0.0

[bus_1]
eq = false
mute = false
gain = 0.0

[bus_2]
eq = false
mute = false
gain = 0.0

[bus_3]
eq = false
mute = false
gain = 0.0

[bus_4]
eq = false
mute = false
gain = 0.0
