[strip_0]
A1 = true
B1 = true
mono = true
solo = true
mute = true
gain = 0.0

[strip_1]
A1 = false
B1 = false
mute = false
gain = 0.0

[strip_2]
A1 = false
B1 = false
mute = false
gain = 0.0

[bus_0]
eq = false
mute = false
gain = 0.0

[bus_1]
eq = false
mute = false
gain = 0.0
